name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo-fonte
      uses: actions/checkout@v2

    - name: Copiar arquivos para o servidor EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: .
        target: /home/ubuntu/api-wave-base

    - name: SSH para o servidor EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/api-wave-base
          yarn
          sudo docker-compose up -d
          sudo ufw allow 3000/tcp
          sudo ufw allow 3000/udp
          yarn typeorm migration:run
          sudo pm2 start "yarn dev" --name Wave 